# Generated by Django 5.0 on 2024-10-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='title',
            field=models.CharField(default='Random Title', max_length=20),
            preserve_default=False,
        ),
    ]
